/**
 * RFC 9457 — Problem Details for HTTP APIs
 * @see https://www.rfc-editor.org/rfc/rfc9457
 */
export type ProblemDetail = {
  /** URI reference identifying the problem type */
  type: string;
  /** HTTP status code generated by the origin server */
  status: number;
  /** Short, human-readable summary of the problem type */
  title: string;
  /** Human-readable explanation specific to this occurrence */
  detail?: string;
  /** URI reference identifying the specific occurrence */
  instance?: string;
  /** Zod field-level validation errors (extension member) */
  fieldErrors?: Record<string, string[]>;
  /** Structured validation errors with JSON Pointer (extension member) */
  errors?: Array<{ pointer: string; detail: string }>;
};

/** Problem type URI constants */
export const ProblemType = {
  VALIDATION_ERROR: "/problems/validation-error",
  NOT_FOUND: "/problems/not-found",
  UNIQUE_VIOLATION: "/problems/unique-violation",
  FOREIGN_KEY_VIOLATION: "/problems/foreign-key-violation",
  UNAUTHORIZED: "/problems/unauthorized",
  FORBIDDEN: "/problems/forbidden",
  TOO_MANY_REQUESTS: "/problems/too-many-requests",
  INTERNAL_ERROR: "/problems/internal-error",
} as const;
